//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AritySystems.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommercialInvoiceItem
    {
        public int Id { get; set; }
        public int CommercialInvoiceId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> RMB_ProductPrice { get; set; }
        public Nullable<decimal> Dollar_ProductPrice { get; set; }
    
        public virtual CommercialInvoice CommercialInvoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
